
import {MRT_Localization} from "material-react-table/dist/localization";
export const LOCALE_ES: any = {
    // @ts-ignore
    actions: 'Acciones',
    columnActions: 'Acciones de columna',
    clearSort: 'Ordenar claro',
    groupByColumn: 'Agrupar por {column}',
    hideColumn: 'Ocultar columna de {column}',
    sortByColumnAsc: 'Ordenar por {column} ascendente',
    sortByColumnDesc: 'Ordenar por {column} descendiendo',
    ungroupByColumn: 'Desagrupar por {column}',
    hideAll: 'Ocultar todo',
    showAll: 'Mostrar todo',
    expandAll: 'Expandir todo',
    expand: 'Expandir',
    clearFilter: 'Filtro claro',
    filterByColumn: 'Filtrar por {column}',
    cancel: 'Cancelar',
    save: 'Salvar',
    rowActions: 'Acciones de fila',
    edit: 'Editar',
    clearSearch: 'Borrar búsqueda',
    search: 'Búsqueda',
    toggleSelectAll: 'Seleccionar todo',
    toggleSelectRow: 'Seleccionar fila',
    showHideColumns: 'Mostrar/Ocultar columnas',
    toggleDensePadding: 'Alternar relleno denso',
    showHideFilters: 'Alternar filtros',
    toggleFullScreen: 'Alternar pantalla completa',
    showHideSearch: 'Alternar búsqueda',
    selectedCountOfRowCountRowsSelected:
        '{selectedCount} de {rowCount} fila(s) seleccionadas',
    groupedBy: 'Agrupados por ',
    thenBy: ', entonces por ',
}
